<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Uffffffffffoooooooooooo" failures="4" tests="8" name="edgetesting" time="96.348" errors="0" timestamp="2024-08-28T19:17:52 IST">
  <testcase classname="testCases.TC01_Account_RegistrationTest" name="Account_registration" time="20.409">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC01_Account_RegistrationTest.Account_registration(TC01_Account_RegistrationTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Account_registration -->
  <testcase classname="testCases.TC02_LoginPage" name="logintest" time="3.524">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC02_LoginPage.logintest(TC02_LoginPage.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
  <testcase classname="testCases.TC03_LoginDPT" name="Login_DAtadrivenTest" time="11.349"/>
  <testcase classname="testCases.TC03_LoginDPT" name="Login_DAtadrivenTest" time="11.22"/>
  <testcase classname="testCases.TC03_LoginDPT" name="Login_DAtadrivenTest" time="1.984"/>
  <testcase classname="testCases.TC03_LoginDPT" name="Login_DAtadrivenTest" time="11.25"/>
  <testcase classname="testCases.TC03_LoginDPT" name="Login_DAtadrivenTest" time="11.209">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC03_LoginDPT.Login_DAtadrivenTest(TC03_LoginDPT.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Login_DAtadrivenTest -->
  <testcase classname="testCases.TC03_LoginDPT" name="Login_DAtadrivenTest" time="2.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC03_LoginDPT.Login_DAtadrivenTest(TC03_LoginDPT.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Login_DAtadrivenTest -->
</testsuite> <!-- edgetesting -->
